### PR TITLE
Added proxy functionality

### PR DESCRIPTION
**Pull request by tonk**
The module had no `proxy` possibility. Added, because we need that :-)

### CODE REVIEW

**Comment by nexecook** [comment]
Hey @tonk, sorry for the delay but would you mind squashing the two commits into one?

**Comment by tonk** [comment]
No worries. I will give it a shot, but I'm always fighting with squash and rebase.
I'll give it a go tomorrow.

**Comment by tonk** [comment]
Squashed it.

**Comment by nexecook** [comment]
Thanks!

**Pull request merged**
